# Generated by Django 4.2.30 on 2026-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calories_goal',
            field=models.FloatField(default=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание'), ('gain', 'Набор массы')], max_length=10),
        ),
    ]
