# Generated by Django 4.2.30 on 2026-05-15 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_weightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
